### ISSUE TITLE
Running sendgrid-report-php without Composer

### ISSUE THREAD

**Issue by paoga87** [fcosrno/sendgrid-report-php#4]
Hello @fcosrno,

If I am not using Composer (temporarily); which files are required to run your library extension package?

**Comment by fcosrno** [comment]
Hi @paoga87,

If you do not wish to use Composer, you can [download the latest release](https://github.com/fcosrno/sendgrid-report-php/archive/master.zip). Then include the two library files from the src folder.

```
require_once('/path/to/SendGrid.php');
require_once('/path/to/Report.php');
```

You can then use the libraries like in the documentation:

```
$sendgrid = new Fcosrno\SendGridReport\SendGrid('username', 'password');
$report = new Fcosrno\SendGridReport\Report();

```

**Comment by paoga87** [comment]
Hi @fcosrno,
Thank you for your quick response.
