### ISSUE TITLE
requires sendgrid/sengrid 2.*

### ISSUE THREAD

**Issue by Razorholt** [fcosrno/sendgrid-report-php#5]
Hello -

I just installed sendgrid-php 5.1.2 and when I tried to install your code, I got this:

 Problem 1
    - Installation request for fcosrno/sendgrid-report 1.* -> satisfiable by fco                                                 srno/sendgrid-report[v1.0.0].
    - fcosrno/sendgrid-report v1.0.0 requires sendgrid/sendgrid 2.* -> satisfiab                                                 le by sendgrid/sendgrid[2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.1.0, 2.1.1,                                                  2.2.0, 2.2.1] but these conflict with your requirements or minimum-stability.

I'm assuming I can still use fcosmo outside composer without creating any conflicts, correct?

Thanks,
-R

**Comment by fcosrno** [comment]
Sure, you can try installing outside composer. Check out[ the last paragraph in the Installation section of the documentation](https://github.com/fcosrno/sendgrid-report-php#installation).
